package ch.admin.bit.jeap.cli.commands;

import ch.admin.bit.jeap.cli.backfill.PasBackfillException;
import ch.admin.bit.jeap.cli.backfill.PasBackfillService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.shell.core.command.annotation.Command;
import org.springframework.shell.core.command.annotation.Option;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.UUID;

@Component
public class PasBackfillCommands {

    private final PasBackfillService pasBackfillService;
    private final InputStream inputStream;

    @Autowired
    public PasBackfillCommands(PasBackfillService pasBackfillService) {
        this(pasBackfillService, System.in);
    }

    PasBackfillCommands(PasBackfillService pasBackfillService, InputStream inputStream) {
        this.pasBackfillService = pasBackfillService;
        this.inputStream = inputStream;
    }

    @Command(name = {"pas-backfill", "send"}, description = "Submit a backfill job YAML to the PAS", group = "PAS Backfill")
    public void send(
            @Option(longName = "file", required = true, description = "Path to backfill-job.yaml") String file,
            @Option(longName = "job-id", required = false, description = "Unique job UUID (generated by caller)") String jobId,
            @Option(longName = "url", required = true, description = "PAS base URL, e.g. https://pas.example.com") String url,
            @Option(longName = "access-token", required = false, description = "Access token for the PAS service (default: stdin)") String accessToken) {

        String resolvedJobId = jobId == null || jobId.isBlank() ? UUID.randomUUID().toString() : jobId;
        System.out.println(pasBackfillService.send(Path.of(file), resolvedJobId, url, resolveAccessToken(accessToken)));
    }

    @Command(name = {"pas-backfill", "report"}, description = "Read the backfill job report from the PAS", group = "PAS Backfill")
    public void report(
            @Option(longName = "job-id", required = true) String jobId,
            @Option(longName = "url", required = true) String url,
            @Option(longName = "output", required = false, description = "Output file path (default: stdout)") String output,
            @Option(longName = "access-token", required = false, description = "Access token for the PAS service (default: stdin)") String accessToken) {

        Path outputPath = output == null || output.isBlank() ? null : Path.of(output);
        System.out.println(pasBackfillService.report(jobId, url, outputPath, resolveAccessToken(accessToken)));
    }

    private String resolveAccessToken(String accessToken) {
        if (accessToken != null && !accessToken.isBlank()) {
            return accessToken;
        }
        try {
            String stdinToken = new String(inputStream.readAllBytes(), StandardCharsets.UTF_8).trim();
            if (stdinToken.isBlank()) {
                throw new PasBackfillException("Missing access token. Provide --access-token or pipe the token to stdin.");
            }
            return stdinToken;
        } catch (IOException e) {
            throw new PasBackfillException("Could not read access token from stdin: " + e.getMessage());
        }
    }
}
